### ISSUE TITLE
Content in multiple sections in docs.html is corrupted

### ISSUE THREAD

**Issue by j-h-scheufen** [ethsociety/plasma-website#22]
After starting the website locally, the content of multiple sections in the "Plasma 101" (docs.html) section presents itself as unintelligible gibberish.

Example:

```
Challenge Period
For who thoroughly her boy estimating conviction. Removed demands expense account in outward tedious do. Particular way thoroughly unaffected projection favourable mrs can projecting own. Thirty it matter enable become admire in giving. See resolved goodness felicity shy civility domestic had but. Drawings offended yet answered jennings perceive laughing six did far.

Instrument cultivated alteration any favourable expression law far nor. Both new like tore but year. An from mean on with when sing pain. Oh to as principles devonshire companions unsatiable an delightful. The ourselves suffering the sincerity. Inhabit her manners adapted age certain. Debating offended at branched striking be subjects.

Exit strategies
Whole wound wrote at whose to style in. Figure ye innate former do so we. Shutters but sir yourself provided you required his. So neither related he am do believe. Nothing but you hundred had use regular. Fat sportsmen arranging preferred can. Busy paid like is oh. Dinner our ask talent her age hardly. Neglected collected an attention listening do abilities.

The him father parish looked has sooner. Attachment frequently terminated son. You greater nay use prudent placing. Passage to so distant behaved natural between do talking. Friends off her windows painful. Still event you being think nay for. In three if aware he point it. Effects warrant me by no on feeling settled resolve.
```

 Other sections in `Plasma by example` are also affected: Overview, Architecture, CLI Documentation

There might be more ... I stopped reading further.

**Comment by j-h-scheufen** [comment]
I'm just now realizing that the entire website still contains "placeholder" texts in most of the sections. If this is still all "under construction", please consider putting a disclaimer at the beginning of the site and in the README! This repo was mentioned and promoted on social media and left the impression that it's finished (hint: not having a `master` branch would've also signaled that the site is not ready, yet).
You can close this ticket, if the above is correct and the site is still being built.

**Comment by kfichter** [comment]
Sorry! Yes, this is under construction. Content will start to be published today as we try to wrap things up for the IC3 boot camp. I'll change the readme!

**Comment by kfichter** [comment]
README updated, closing.
