### ISSUE TITLE
Determine content type

### ISSUE THREAD

**Issue by kfichter** [ethsociety/plasma-website#3]
Should this be mainly text? Text + video? We probably can't do video this week, but I can get some recording tools and do the video when I'm back in Bangkok.

I think mainly text would be nice because it promotes as much community content as possible.

**Comment by barrasso** [comment]
Text, links, and example code would be a nice start. We can always add video content later.

**Comment by parthgargava** [comment]
Yes, let's just do plain text and animations/images with cartoons explaining all scenarios
